sudo: required
language: nodejs
services:
- docker
env:
  global:
  - REGISTRY_USER=aggippbot
  - secure: "Yc05BZ0cBfQg+gL1+j/XSbx46lGHNr1jdN4X5FqYYrF/IuP9hdpDm790z8kqJx6tlsfgbtpJhUOR3EkF3bAv2SPLiVnNVIifXWk6fCyjLxO/8kONyagLmV9+rfqeYxk2N8lCp4e+A4OLJbQf7wpUQ6Ya+dnTC7D4YrHtEeyIyYGFWyqG94CBuuhjYv9Os940ihj1n15ovwSrc4p6Um3zhpNBRf23CnMkRvoSFRSj0A6VwaDom+CPBlFOLsJdXEZxlk6kl98RJClhML9koZhLm0C8KgVSGXqvxuTHn7eiwGMp4T1OiF3FCFH9dDCMrx4AqIN9LYlkP/GxTluRYclgkW6Ikz3DHjPSc5vyrMRMbba3IrExlH1qt0Xd4fFfOvDNwOC6VpSSABH4dOCsXg3LFrqpSF+7lwWBnlykEdRGjFLJVFxg/K0mLgRQKXbCvFM8DNIF/ak49GnBzHorokbYynRAKT2ZZTKpO/J34DEidZ8xVP4WR+6AKkOjiQRz0nrjytr3R6X4Iuw3ovUlhg7/ma2jAAsHBdXILYQwH8U2VjaZmSBJDYfIgtjAmJsHHC5hkNt4v0fXF5sUGIsO+5DpP4Z6516etdWXWlf6562grLUB5zH+iOEqBeYucHNgMunlryconnk1AkQs5TuGCFMD5KFyPf98IBRiWB1tQK/cReQ="
before_script:
- docker pull aggipp/mathmlben || true
script:
- docker build --pull --cache-from aggipp/mathmlben --tag aggipp/mathmlben .
- docker run aggipp/mathmlben
after_script:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push aggipp/mathmlben
  on:
    branch: master
